#region Using ...
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using HotelReservationService.Entity.Entities;
#endregion

/*
* Generated by: CodeGenerator Version 1.0.0.0
* Generated for: SmarttechSys
*/
namespace HotelReservationService.Core.IRepositories
{
    /// <summary>
    /// 
    /// </summary>
    public interface IRolesRepositoryAsync : Base.IBaseServiceRepositoryAsync<Role, long>
    {

    }
}
