#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace HotelReservationService.Business.Services.Base
{
	/// <summary>
	/// 
	/// </summary>
	public interface BaseService
	{

	}
}
