#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Common.Enums
{
	/// <summary>
	/// 
	/// </summary>
	public enum Order : byte
	{
		Ascending = 0,
		Descending
	}
}
