#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Core.Common
{
	/// <summary>
	/// Represents a pointer for method takes 
	/// no parameters and returns void that 
	/// will be pointed to be excuted later.
	/// </summary>
	public delegate void InstructionSetDelegate();
}
