#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Common.Interfaces
{
	/// <summary>
	/// 
	/// </summary>
	public interface IDeletionSignature
	{
		#region Properties
		public bool IsDeleted { get; set; }
		public DateTime? DeletionDate { get; set; }
		//public DateTime? FirstDeletionDate { get; set; }
		//public DateTime? LastDeletionDate { get; set; }
		public long? DeletedByUserId { get; set; }
		public bool? MustDeletedPhysical { get; set; }
		#endregion
	}
}
