#region Using ...
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Common.Interfaces
{
	/// <summary>
	/// 
	/// </summary>
	public interface IEntityCreatedUserSignature
	{
		#region Properties
		/// <summary>
		/// Gets or sets entity CreatedByUserId
		/// </summary>
		long? CreatedByUserId { get; set; }
		#endregion
	}
}
