#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace HotelReservationService.Common.Enums
{
    /// <summary>
    /// 
    /// </summary>
    public enum Permissions
    {
        ReservationAdd = 1,
        ReservationEdit= 2,
        ReservationView = 3,
        ReservationList = 4,
        ReservationDelete = 5,
    }
}

