#region Using ...
using Framework.Common.Enums;
using Framework.Common.Interfaces;
using HotelReservationService.Common.Enums;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
#endregion

/*
* Generated by: CodeGenerator Version 1.0.0.0
* Generated for: SmarttechSys
*/
namespace HotelReservationService.Entity.Entities
{
    public class Permission : IEntityIdentity<long>
    {
        #region Constructors
        public Permission()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
        #endregion

        #region Properties

        #region IEntityIdentity<long>
        public long Id { get; set; }
        #endregion

        public string Name { get; set; }
        public int Code { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
        #endregion
    }
}
