#region Using ...
using Framework.Common.Enums;
using Framework.Common.Interfaces;
using HotelReservationService.Common.Enums;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
#endregion

/*
* Generated by: CodeGenerator Version 1.0.0.0
* Generated for: SmarttechSys
*/
namespace HotelReservationService.Entity.Entities
{
    
    public class RolePermission : IEntityIdentity<long>
    {

        #region Properties

        #region IEntityIdentity<long>
        public long Id { get; set; }
        #endregion


        public Nullable<long> RoleId { get; set; }
        public virtual Role Role { get; set; }
        public Nullable<long> PermissionId { get; set; }
        public virtual Permission Permission { get; set; }

        #endregion
    }
}
