#region Using ...
using HotelReservationService.Core.Models.ViewModels;
using HotelReservationService.Core.Models.ViewModels.Reservation;
using HotelReservationService.Core.Models.ViewModels.UserManagement.User;
using HotelReservationService.Entity.Entities;


#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace HotelReservationService.Core
{
    /// <summary>
    /// Provides an extention methods that used for mapping.
    /// </summary>
    public static class Extentions
    {
        #region User
        public static User ToEntity(this UserViewModel model, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<UserViewModel, User>(model);
            return result;
        }
        public static UserViewModel ToModel(this User entity, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<User, UserViewModel>(entity);
            return result;
        }

        public static User ToInputEntity(this UserInputModel model, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<UserInputModel, User>(model);
            return result;
        }
        public static UserInputModel ToInputModel(this User entity, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<User, UserInputModel>(entity);
            return result;
        }
        #endregion

        #region Reservation
        public static Reservation ToEntityLight(this ReservationLightViewModel model, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<ReservationLightViewModel, Reservation>(model);
            return result;
        }
        public static ReservationLightViewModel ToModelLight(this Reservation entity, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<Reservation, ReservationLightViewModel>(entity);
            return result;
        }

        public static Reservation ToEntity(this ReservationViewModel model, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<ReservationViewModel, Reservation>(model);
            return result;
        }
        public static ReservationViewModel ToModel(this Reservation entity, AutoMapper.IMapper mapper)
        {
            var result = mapper.Map<Reservation, ReservationViewModel>(entity);
            return result;
        }
        #endregion
    }
}
