#region Using ...
using Framework.Core.Common;
using System;
using System.Collections.Generic;
using System.Text;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Core.Models
{
	public class BaseFilter
	{
		public string Sorting { get; set; }
		public Pagination Pagination { get; set; }
	}
}
