#region Using ...
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace Framework.Core.IRepositories
{
	/// <summary>
	/// 
	/// </summary>
	public interface IUnitOfWork
	{
		#region Methods
		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		int Commit();
		#endregion
	}
}
