#region Using ...
using Framework.Core.IRepositories;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using HotelReservationService.Core.IRepositories;
using HotelReservationService.DataAccess.Contexts;
#endregion

/*
 * Generated by: CodeGenerator Version 1.0.0.0
 * Generated for: SmarttechSys
 */
namespace HotelReservationService.DataAccess.Repositories
{
	/// <summary>
	/// 
	/// </summary>
	public class UnitOfWork : IUnitOfWork
	{
		#region Data Members
		private HotelReservationServiceContext _context;
		#endregion

		#region Constructors
		/// <summary>
		/// Initializes a new instance from type 
		/// UnitOfWork.
		/// </summary>
		/// <param name="context"></param>
		public UnitOfWork(HotelReservationServiceContext context)
		{
			this._context = context;
		}
		#endregion

		#region IUnitOfWork
		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		public int Commit()
		{
			var result = this._context.SaveChanges();
			return result;
		}		
		#endregion
	}
}
